version: '3'
services:
  db_postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env.development
  db_redis:
    image: redis
    depends_on:
      - db_postgres
    restart: always
    ports:
      - 6379:6379
  app:
    build: .
    depends_on:
      - db_postgres
    restart: always
    ports:
      - 9000:9000
    env_file:
      - .env.development
    environment:
      ENVIRONMENT_NAME: 'development'
